# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc95cd1769b2e47774f3f8f905c32c326647453215b4383736731901f77bda1c04fb20bdfd2a90d3c823d7e4b7e43fff4a4534fc2a6fdcd1d0e421aac3bfa55b

test:
  secret_key_base: 7037e31fb921d415f452fb0853a11f0339a871b846c3e1bd55657957e8061fc2625377e78f5d45260b2cccf7b529f5787788cef226e007ed05a8c5ca35f35fc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
