# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f12a926393a750eed9c0a5e1c6ae3645cb60060101a1d255a9f185a89db8577f7a7c5b57f0597b5c708e2ae3b7982b0c0731070a57eb6f3c0f1ee25ac4d6bc6

test:
  secret_key_base: 8e425303b80fc7855aa73afd6d1e704f32a9c2ea2ea79ffa5516fb3377b9580e5be55f6d0f95e862e0ae12cc8c13fa5fc092bd3addfe3ea86abb1f2f3fc964a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
