# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('courses', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_courses', to='courses.Courses')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_users', to='login_app.Users')),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='course_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allusers', to='login_app.Users'),
        ),
    ]
